fn main() -> Result<(), failure::Error>{
    notifier::run()
}
