fn main() -> Result<(), failure::Error>{
    notif::run()
}
